apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: log-app:latest
          imagePullPolicy: Never
          command: ["python", "-m", "app.consumer"]
          envFrom:
            - secretRef:
                name: app-secrets
